name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build bff-benefit-module
        run: mvn -B -f bff-benefit-module clean package
      - name: Build ms-benefit-module
        run: mvn -B -f ms-benefit-module clean package
